### ISSUE TITLE
IDE error occured when starting IntelliJ

### ISSUE THREAD

**Issue by alexanderschikora** [chylex/IntelliJ-Colored-Icons#2] opened 2023-11-30 10:52 UTC
Icons are displayed, but error occured:

Calling `ClassLoader#getResource` with leading slash doesn't work; strip

### 1st Error
com.intellij.diagnostic.PluginException: /icons/toolwindows/notifications.svg [Plugin: com.chylex.intellij.coloredicons]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.kt:603)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getUrl(RasterizedImageDataLoader.kt:66)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.kt:84)
	at com.intellij.util.IconUtil.scaleOrLoadCustomVersion(IconUtil.kt:512)
	at com.intellij.openapi.wm.impl.ToolWindowIcon.scale(ToolWindowIcon.kt:38)
	at com.intellij.openapi.wm.impl.ToolWindowIcon.scale(ToolWindowIcon.kt:17)
	at com.intellij.ide.actions.ActivateToolWindowAction.updatePresentation(ActivateToolWindowAction.java:118)
	at com.intellij.ide.actions.ActivateToolWindowAction.ensureToolWindowActionRegistered(ActivateToolWindowAction.java:54)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing(ToolWindowSetInitializer.kt:161)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing$default(ToolWindowSetInitializer.kt:152)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:138)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:45)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$1.invokeSuspend(ToolWindowSetInitializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### 2nd Error
com.intellij.diagnostic.PluginException: /icons/toolwindows/notifications.svg [Plugin: com.chylex.intellij.coloredicons]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.kt:603)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getUrl(RasterizedImageDataLoader.kt:66)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.kt:84)
	at com.intellij.openapi.util.IconLoader.loadCustomVersionOrScale(IconLoader.kt:112)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.scaleIcon(SquareStripeButton.kt:118)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.createPresentation(SquareStripeButton.kt:111)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.access$createPresentation(SquareStripeButton.kt:1)
	at com.intellij.openapi.wm.impl.SquareStripeButton.<init>(SquareStripeButton.kt:28)
	at com.intellij.toolWindow.ToolWindowPaneNewButtonManager.createStripeButton(ToolWindowPaneNewButtonManager.kt:131)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1076)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:176)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by chylex** [comment] 2023-12-01 00:46
Duplicate of #1, new UI is not supported. Since the exception only happens in this unsupported scenario, I haven't released an update yet, I will probably do an update once 2023.3 comes out since I noticed it has broken some icons.

**Closed as not planned by chylex** 2023-12-01 00:46 UTC
